CREATE TABLE USER_INFORMATION (
    UserID BIGINT NOT NULL PRIMARY KEY,
    UserFirstName TINYTEXT NOT NULL,
    UserLastName TINYTEXT NOT NULL,
    UserEmailAddress MEDIUMTEXT NOT NULL UNIQUE,
    UserPassword VARCHAR(30) NOT NULL,
    UserAccessStartDate DATE NOT NULL,
    UserAccessEndDate DATE
);

CREATE TABLE USER_ROLES (
    UserRoleID BIGINT NOT NULL PRIMARY KEY,
    RoleName TINYTEXT NOT NULL UNIQUE,
    ShortRoleDescription MEDIUMTEXT,
    CreateAccess BOOLEAN NOT NULL,
    ReadAccess BOOLEAN NOT NULL,
    UpdateAccess BOOLEAN NOT NULL,
    DeleteAccess BOOLEAN NOT NULL
);

CREATE TABLE USER_ROLE_ASSIGNMENT (
    UserID BIGINT NOT NULL,
    UserRoleID BIGINT NOT NULL,
    PRIMARY KEY (UserID, UserRoleID),
    FOREIGN KEY (UserID) REFERENCES USER_INFORMATION(UserID),
    FOREIGN KEY (UserRoleID) REFERENCES USER_ROLES(UserRoleID)
);

CREATE TABLE PWW_ENTRY_CREATORS (
    PublishedPWWEntryID BIGINT NOT NULL,
    UserID BIGINT NOT NULL,
    DateEdited DATE NOT NULL,
    ShortDescriptionOfChange MEDIUMTEXT,
    PRIMARY KEY (PublishedPWWEntryID, UserID),
    FOREIGN KEY (UserID) REFERENCES USER_INFORMATION(UserID)
);

CREATE TABLE PWW_CITED_WORKS (
    PWWEntryID BIGINT NOT NULL,
    PWWCitedWorkCitationID BIGINT NOT NULL,
    GivenCitation MEDIUMTEXT,
    DOI MEDIUMTEXT,
    PRIMARY KEY (PWWEntryID, PWWCitedWorkCitationID),
    FOREIGN KEY (PWWEntryID) REFERENCES PWW_ENTRY(PWWEntryID)
);

CREATE TABLE TOPIC_TAGS (
    TopicID BIGINT NOT NULL PRIMARY KEY,
    TopicName MEDIUMTEXT NOT NULL UNIQUE
);

CREATE TABLE PWW_TAGGED_TOPICS (
    PWWEntryID BIGINT NOT NULL,
    TopicID BIGINT NOT NULL,
    PRIMARY KEY (PWWEntryID, TopicID),
    FOREIGN KEY (PWWEntryID) REFERENCES PWW_ENTRY(PWWEntryID),
    FOREIGN KEY (TopicID) REFERENCES TOPIC_TAGS(TopicID)
);
