CREATE ROLE Editor;
GRANT ALL PRIVILEGES ON PWW_DATABASE.* TO Editor WITH GRANT OPTION;

CREATE ROLE DataEntry;
GRANT SELECT, INSERT, UPDATE, DELETE ON PWW_DATABASE.* TO DataEntry;

CREATE ROLE Referee;
GRANT SELECT ON PWW_DATABASE.PRIVATE_ACCESS_VIEW TO Referee;

-- CREATE ROLE GeneralUser;
-- GRANT SELECT ON PWW_DATABASE.PUBLIC_ACCESS_VIEW TO Editor;