DROP ROLE if exists Editor;
CREATE ROLE Editor;
GRANT ALL PRIVILEGES ON PWW_DATABASE.* TO Editor WITH GRANT OPTION;

DROP ROLE if exists DataEntry;
CREATE ROLE DataEntry;
GRANT SELECT, INSERT, UPDATE, DELETE ON PWW_DATABASE.* TO DataEntry;

DROP ROLE if exists Referee;
CREATE ROLE Referee;
GRANT SELECT ON PWW_DATABASE.PRIVATE_ACCESS_VIEW TO Referee;

DROP ROLE if exists GeneralUser;
CREATE ROLE GeneralUser;
GRANT SELECT ON PWW_DATABASE.PUBLIC_ACCESS_VIEW TO Editor;